### ISSUE TITLE
Peer Review Comments

### ISSUE THREAD

**Issue by ian-shryock** [esme-castro/dataviz_final#14]
This code was very well written! I especially appreciate how thoroughly commented everything is, it was really easy for me to follow the logic of what was happening. Although I couldn't see the interactive plot in all of it's glory yet, that seems like a really good way to include all of the information you're hoping to provide, while also reducing the cognitive load as much as possible. One idea I might suggest for this is to have the interactivity portion enable viewers to highlight data from geographical regions by hovering over the key or, alternatively, highlight the PE requirements by hovering. (I have no idea how easy this is to implement, kudos to y'all for delving into the interactivity zone...I was not so bold). 

@datalorax

**Comment by datalorax** [comment]
Thanks Ian! Nice review. Hopefully you can get the PR to work as well.
